// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Resposta struct {
	Sum       int   `json:"sum"`
	Positions []int `json:"positions"`
	Sublist   []int `json:"sublist"`
}
